#!/usr/bin/env bash
#loop again
count=0
while [ $count -le 100 ]
do
 echo "$count"
 if [ $count=$(($count/3)) && $count=$(($count/5)) ]
 then
   echo "fizzbuzz"
 elif [ $count=$(($count/3)) ]
 then 
   echo "fizz"
 elif [ $count=$(($count/5)) ]
 then 
   echo "buzz"
 fi
 (( count++ ))
done
