#!/usr/bin/env bash
#loop again
for count in (1..100)
do
 if (( count%3 == 0 && count%5 == 0)) 
 then
   echo "fizzbuzz"
 elif (( count%3 == 0 )) 
 then 
   echo "fizz"
 elif (( count%5 == 0 )) 
 then 
   echo "buzz"
 else 
   echo "$count"	 
 fi
 (( count++ ))
done
