#!/usr/bin/env bash
#nineth
file="/var/run/myscript.pid"
echo $$ > $file

while true;
do
  echo "To infinity and beyond"
  sleep 1
done
delete="rm -rf $file"
exit_file="exit 0"
trap 'echo "I hate the kill command"' SIGTERM
trap 'echo"$delete $exit_file"' SIGQUIT
trap 'echo "Y U no love me?!"' SIGINT
