#!/usr/bin/env bash
#management
pid=$$
file="/var/run/my_process.pid"

start() {
    if [ -f "$file" ]; then
       echo "manage_my_process is already running."
       exit 1
    fi
    ./manage_my_process &
    echo $! > "$file"
    echo "manage_my_process started"
}

stop() {
    if [ ! -f "$file" ]; then
       echo "manage_my_process is not running"
       exit 1
    fi

    pid=$(cat "$file")
    kill "$pid"
    rm "$file"
    echo "manage_my_process"

}
restart() {
    stop
    start
    echo "manage_my_process restarted"
}

case "$1" in
     start)
          start
          ;;
     stop)
          stop
          ;;
     restart)
           restart
           ;;
     *)
       echo "Usage: $0 {start|stop|restart}"
       exit 1
       ;;
esac