#!/user/bin/env bash
#using top

for pid in /proc/*/; do
  pid=${pid%*/}
  pid=${pid##*/}
  name=$(cat /proc/"$pid"/comm)

  if [ "$name" == *"bash"* ]; then
      echo "$pid $name"
  else 
      echo "bash not found"
   
  fi
done
