#!/usr/bin/env bash
#using top
# shellcheck disable=SC2009
pids=$(pgrep -f bash)
for pid in $pids; do
	process_name=$(cat /proc/$pid/cmdline | tr '\0' ' ')
	echo "Pid: $pid, Process Name: $process_name"
done
