#!/usr/bin/env bash
#using top
# shellcheck disable=SC2009
script_pid=$$

pids=$(ls /proc | grep -E '^[0-9]+$')

for pid in $pids; do
   if ps -e | findstr bash; then
      process_name=$(tr '\0' ' ' < /proc/$pid/cmdline )
	  echo "$pid $process_name"
   fi
done